### ISSUE TITLE
the project game is too big

### ISSUE THREAD

**Issue by stickylabdev** [JordanSchuetz/Realtime-Unity-Leaderboards-with-PubNub#1]
hmmmmmmmm its too big bro

**Comment by JordanSchuetz** [comment]
This is a standard unity project size.  I uploaded the unity project for easy instant setup.  It shouldn't be tough to manually download the assets and code and piece them together yourself.

**Comment by stickylabdev** [comment]
sir ,,, but it you should make unity package then upload it on realese section

**Comment by stickylabdev** [comment]
and  C++ 98.5% ????????? i think unity only C# its weird

**Comment by JordanSchuetz** [comment]
Hi Muafakul,

Good suggestion.  That was our plan once I created a more established package.
